spring.application.name=InvestYou

spring.datasource.url=jdbc:mysql://localhost/invest_you
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT api key
api.security.token.secret=${JWT_SECRET:$2a$12$4pPuGUmqTyzDCrkM7Dir1.ngxnLCy1PzCbwS041fDOX8j1QmjUH4G}

api.security.token.subject=investyou
